server:
  service:
    url: http://localhost:8080/
  port: 8080

spring:
  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console  # H2 Console Path
  # Database Setting Info
  datasource:
    driver-class-name: org.h2.Driver  # Database? H2
    url: jdbc:h2:mem:test
    username: test
    password: 1234
    initialization-mode: always
    platform: h2
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true