drop table if exists todo_entity CASCADE;

create table todo_entity (
    id bigint generated by default as identity,
    title varchar(255) not null,
    todo_order integer not null,
    completed boolean not null,
    primary key (id)
);